<a href="https://colab.research.google.com/github/Ricardo-FPSilva/CienciaDeDados-6Semestre/blob/main/Atividade_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [ ]:
data = {
    "idade": [25, 30, 22, None, 40, 35, None],
    "renda": [2000, 3000, 1500, 2500, 4000, 3500, 2800],
    "genero": ["F", "M", "F", "F", "M", "M", "F"],
    "compra": ["Sim", "Não", "Sim", "Sim", "Não", "Não", "Sim"]
}

df = pd.DataFrame(data)

df

   idade  renda genero compra
0   25.0   2000      F    Sim
1   30.0   3000      M    Não
2   22.0   1500      F    Sim
3    NaN   2500      F    Sim
4   40.0   4000      M    Não
5   35.0   3500      M    Não
6    NaN   2800      F    Sim

In [ ]:
imputer = SimpleImputer(strategy="mean")

df["idade"] = imputer.fit_transform(df[["idade"]])

df

   idade  renda genero compra
0   25.0   2000      F    Sim
1   30.0   3000      M    Não
2   22.0   1500      F    Sim
3   30.4   2500      F    Sim
4   40.0   4000      M    Não
5   35.0   3500      M    Não
6   30.4   2800      F    Sim

In [ ]:
encoder = LabelEncoder()

df["genero"] = encoder.fit_transform(df["genero"])
df["compra"] = encoder.fit_transform(df["compra"])

df

   idade  renda  genero  compra
0   25.0   2000       0       1
1   30.0   3000       1       0
2   22.0   1500       0       1
3   30.4   2500       0       1
4   40.0   4000       1       0
5   35.0   3500       1       0
6   30.4   2800       0       1

In [ ]:
X = df[["idade", "renda", "genero"]]
y = df["compra"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
model = DecisionTreeClassifier()

model.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
predictions = model.predict(X_test)

predictions

array([1, 0, 0])

In [ ]:
accuracy = accuracy_score(y_test, predictions)

print("Acurácia:", accuracy)

Acurácia: 1.0